name: some-reusable-workflow
on:
  workflow_call: 
    secrets:
      TEST_SECRET:
        required: true

jobs:
  job1:
    name: JOB 1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Hello, world"
  job2:
    name: JOB 1
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Step 1
        run: echo "Hello, world 2"
